### ISSUE TITLE
shinytouch hangs

### ISSUE THREAD

**Issue by luka177** [cameron-martin/shinytouch#15]
I run app, on Linux Mint 19.2 and windows 7 sp1. On both sameproblem, so probably i am doing something wrong.  So i am calibrating it, by putting finger on red dot and clicking on finger in video stram. 
![image](https://user-images.githubusercontent.com/15714420/78505277-1ed24180-777b-11ea-97bf-5a17cdc6ec33.png) like this.
Then it moves my screan to stream 
![image](https://user-images.githubusercontent.com/15714420/78505320-68bb2780-777b-11ea-8612-ce6766356c13.png). and nothing chages when i move my finger, or clickred dot

**Comment by luka177** [comment]
second photo is very bad due to recurse photo in photo

**Comment by luka177** [comment]
Sadly i cant reelly help in development, due to i dont know typescript at all. Mb i can update python version?

**Comment by cameron-martin** [comment]
The redevelopment of this is very unfinished, and what you're seeing is where I got to. Most importantly I never got round to doing the part that determines the position of the finger in the frame.

I also don't think I'll get round to finishing it any time soon, as my current side-project of choice is [cameron-martin/tsumego-solver](https://github.com/cameron-martin/tsumego-solver). Sorry!

**Comment by luka177** [comment]
Ok i will try my best with python version. Will move to cv2 and python3.

**Comment by luka177** [comment]
hm cant understand what Perspective must do

**Comment by cameron-martin** [comment]
If I remember correctly, this performs a [perspective projection](https://en.wikipedia.org/wiki/3D_projection#Perspective_projection).
